on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
          working-directory: contracts
      - name: Install dependencies
        run: npm install
        working-directory: contracts
      - name: Install OpenZeppelin Contracts
        run: npm install @openzeppelin/contracts@5.5.0
        working-directory: contracts
      - name: Compile contracts
        run: npx hardhat compile
        working-directory: contracts
      - name: Run Analysis
        uses: outdef/contract-vulnerability-action@v0.1.0
        with:
          solc-version: 0.8.24
          workdir: "contracts"
          files: Governor.sol
          format: "text"
          test-mode: "assertion"
          echidna-contract: Governor.sol
          crytic-args: --hardhat-ignore-compile
          target: "contracts/Governor.sol"
          fail-on: "none"
          slither-config: "slither.config.json"
          mythril-args: "--solc-json mythril.config.json"
          mythril-contract: "contracts/Governor.sol"
